name: gis
channels:
  - conda-forge
  - nodefaults
dependencies:
  # --- Core Python ---
  - python=3.12
  - pip=24.2

  # --- Geo stack (CPU; pinned) ---
  - numpy=1.26.4
  - pandas=2.2.2
  - geopandas=1.0.1
  - shapely=2.0.4
  - pyproj=3.6.1
  - proj=9.3.1
  - proj-data=1.15
  - gdal=3.9.2
  - rasterio=1.3.10
  - rioxarray=0.15.6
  - xarray=2024.02.0
  - netcdf4=1.6.5
  - h5py=3.10.0
  - fiona=1.9.6
  - cartopy=0.23.0
  - s3fs=2024.6.0

  # --- Viz / notebook ---
  - jupyterlab=4.2.5
  - ipykernel=6.29.5
  - ipywidgets=8.1.3
  - matplotlib=3.8.4
  - bokeh=3.4.3
  - holoviews=1.17.1
  - hvplot=0.9.2
  - datashader=0.16.2
  - scikit-image=0.23.2
  - scikit-learn=1.4.2

  # --- Geoparquet (Arrow/Parquet IO for Geo) ---
  - pyarrow=16.1.0
  - pyarrow-hotfix=0.6

  # --- Columnar + SQL: DuckDB / Polars / JupySQL ---
  - duckdb=1.1.3
  - polars=1.12.1
  - sqlalchemy=2.0.30
  - sqlparse=0.5.1

  # --- Optional helpers ---
  - tzdata=2024a

  # --- Git / GitHub CLI ---
  - git
  - gh

  # --- Pip extras ---
  - pip:
      - jupysql==0.10.13
      - leafmap==0.33.4
      - keplergl==0.3.2
      - pydeck==0.9.1
